# Generated by Django 3.0 on 2019-12-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakePattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('smallest_repeating_segment', models.CharField(max_length=200)),
                ('smallest_repeating_segment_size', models.IntegerField()),
                ('num_segments', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
