# Generated by Django 3.0 on 2019-12-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('smallest_repeating_segment', models.CharField(max_length=200)),
                ('smallest_repeating_segment_size', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CakePattern',
        ),
    ]
