# Generated by Django 3.0 on 2019-12-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_auto_20191211_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='pattern',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
