# Generated by Django 3.0 on 2019-12-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_auto_20191211_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
